// <auto-generated />
namespace Volunteers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EmailTempalate_v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailTempalate_v1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003181845181_EmailTempalate_v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
