// <auto-generated />
namespace Volunteers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DeployV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeployV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003190304463_DeployV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
